spring.mail.host=smtp.qq.com
#自己的邮箱名
spring.mail.username=2136947133@qq.com
#授权码
spring.mail.password=obleavzosoggdafa
#smtp服务端口号
spring.mail.port=465
#配置 对smtp服务支持的java类
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.default-encoding=UTF-8

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# 文件实际存储目录（根据你的服务器环境修改）

app.upload.dir=D:/JakartaEE/uploads


app.server.base=http://localhost:9999

